In [1]:
from GUI import GUI
from layout.obj.Compo import Compo
import layout.lib.pairing as pairing
import layout.lib.repetition_recognition as rep
import layout.lib.draw as draw
from sklearn.cluster import DBSCAN

import cv2
import pandas as pd
import math
import numpy as np
import os
from os.path import join as pjoin

In [2]:
# gui = GUI(img_file='E:\\Mulong\\Datasets\\gui\\rico\\combined\\all\\10727.jpg', output_dir='E:\\Mulong\\Result\\rico-layout\\result')

In [3]:
gui = GUI(img_file='data/input/2.jpg')

In [4]:
gui.element_detection(img_resize_longest_side=None)
gui.visualize_element_detection(is_resize_showing=False)

In [5]:
gui.layout_recognition()
gui.visualize_layout_recognition(is_resize_showing=False)

[Layout Recognition Completed in 1.164 s] Input: data/input/2.jpg Output: data/output\layout\2.json

In [6]:
gui.visualize_element_detection(is_resize_showing=False)

In [6]:
gui.visualize_layout_recognition(is_resize_showing=False)

In [16]:
df = gui.compos_df.compos_dataframe

In [9]:
df[df['group'] == 't-3']

,id,class,column_min,column_max,row_min,row_max,height,width,area,center,...,center_row,text_content,children,parent,alignment_in_group,gap,group,pair_to,group_pair,list_item
36,36,Text,1000,1034,67,82,15,34,510,"(1017.0, 74.5)",...,74.5,Reset,-1,-1,v,84,t-3,39,1,0
38,38,Text,994,1078,166,205,39,84,3276,"(1036.0, 185.5)",...,185.5,Connect Connect,-1,-1,v,81,t-3,41,1,1
40,40,Text,996,1078,286,330,44,82,3608,"(1037.0, 308.0)",...,308.0,Connect Connect,-1,-1,v,91,t-3,44,1,2
43,43,Text,994,1081,421,474,53,87,4611,"(1037.5, 447.5)",...,447.5,Connect Connect,-1,-1,v,69,t-3,46,1,3
45,45,Text,997,1080,543,590,47,83,3901,"(1038.5, 566.5)",...,566.5,Connect Connect,-1,-1,v,-1,t-3,47,1,4

In [5]:
gui.cvt_compos_json_to_dataframe()

In [6]:
gui.compos_df.repetitive_group_recognition(show=False)

In [19]:
gui.compos_df.pair_groups()

In [7]:
b = gui.visualize_compos_df('group')

In [21]:
gui.compos_df.calc_gap_in_group()

In [22]:
gui.compos_df.compos_dataframe

,id,class,column_min,column_max,row_min,row_max,height,width,area,center,center_column,center_row,text_content,children,parent,alignment_in_group,gap,group,pair_to,group_pair
0,0,Compo,28,69,58,68,10,41,410,"(48.5, 63.0)",48.5,63.0,-1,-1,-1,h,381,nt-5,-1,-1
1,1,Compo,450,478,63,91,28,28,784,"(464.0, 77.0)",464.0,77.0,-1,-1,-1,h,-1,nt-5,-1,-1
2,2,Compo,28,60,71,77,6,32,192,"(44.0, 74.0)",44.0,74.0,-1,-1,-1,v,4,nt-1,-1,-1
3,3,Compo,284,293,72,81,9,9,81,"(288.5, 76.5)",288.5,76.5,-1,-1,-1,-1,-1,-1,-1,-1
4,4,Compo,28,52,81,89,8,24,192,"(40.0, 85.0)",40.0,85.0,-1,-1,-1,v,-1,nt-1,-1,-1
5,5,Compo,50,70,138,157,19,20,380,"(60.0, 147.5)",60.0,147.5,-1,-1,-1,h,172,nt-4,-1,-1
6,6,Compo,429,459,137,157,20,30,600,"(444.0, 147.0)",444.0,147.0,-1,-1,-1,h,-1,nt-4,-1,-1
7,7,Compo,242,262,141,157,16,20,320,"(252.0, 149.0)",252.0,149.0,-1,-1,-1,h,167,nt-4,-1,-1
8,8,Compo,27,111,195,279,84,84,7056,"(69.0, 237.0)",69.0,237.0,-1,-1,-1,v,15,nt-0,26,1
9,9,Compo,439,484,248,268,20,45,900,"(461.5, 258.0)",461.5,258.0,-1,-1,-1,v,77,nt-2,8,1
10,10,Compo,393,409,251,265,14,16,224,"(401.0, 258.0)",401.0,258.0,-1,-1,-1,h,-1,-1,-1,-1
11,11,Compo,27,111,294,377,83,84,6972,"(69.0, 335.5)",69.0,335.5,-1,-1,-1,v,17,nt-0,28,1
12,12,Compo,438,484,345,366,21,46,966,"(461.0, 355.5)",461.0,355.5,-1,-1,-1,v,81,nt-2,11,1
13,13,Compo,27,111,394,477,83,84,6972,"(69.0, 435.5)",69.0,435.5,-1,-1,-1,v,20,nt-0,30,1
14,14,Compo,309,323,449,465,16,14,224,"(316.0, 457.0)",316.0,457.0,-1,-1,-1,h,-1,-1,-1,-1
15,15,Compo,438,484,447,466,19,46,874,"(461.0, 456.5)",461.0,456.5,-1,-1,-1,v,80,nt-2,13,1
16,16,Compo,27,111,497,580,83,84,6972,"(69.0, 538.5)",69.0,538.5,-1,-1,-1,v,17,nt-0,32,1
17,17,Compo,440,484,546,570,24,44,1056,"(462.0, 558.0)",462.0,558.0,-1,-1,-1,v,78,nt-2,16,1
18,18,Compo,27,110,597,679,82,83,6806,"(68.5, 638.0)",68.5,638.0,-1,-1,-1,v,18,nt-0,34,1
19,19,Compo,438,484,648,669,21,46,966,"(461.0, 658.5)",461.0,658.5,-1,-1,-1,v,81,nt-2,18,1
20,20,Compo,27,110,697,781,84,83,6972,"(68.5, 739.0)",68.5,739.0,-1,-1,-1,v,19,nt-0,36,1
21,21,Compo,438,484,750,772,22,46,1012,"(461.0, 761.0)",461.0,761.0,-1,-1,-1,v,-1,nt-2,20,1
22,22,Compo,291,484,784,878,94,193,18142,"(387.5, 831.0)",387.5,831.0,-1,-1,-1,-1,-1,-1,-1,-1
23,23,Compo,27,110,800,884,84,83,6972,"(68.5, 842.0)",68.5,842.0,-1,-1,-1,v,-1,nt-0,38,1
24,24,Text,186,277,62,83,21,91,1911,"(231.5, 72.5)",231.5,72.5,Contacts,-1,-1,h,-1,-1,-1,-1
25,25,Text,300,318,64,84,20,18,360,"(309.0, 74.0)",309.0,74.0,318,-1,-1,h,-1,-1,-1,-1
26,26,Text,127,252,212,227,15,125,1875,"(189.5, 219.5)",189.5,219.5,Peter Limonez,-1,-1,v,82,t-0,8,1
27,27,Text,129,385,249,263,14,256,3584,"(257.0, 256.0)",257.0,256.0,The road to success is always under construction,-1,-1,v,82,t-0-1,8,1
28,28,Text,126,228,309,327,18,102,1836,"(177.0, 318.0)",177.0,318.0,Sofia Morell,-1,-1,v,84,t-0,11,1
29,29,Text,126,383,345,360,15,257,3855,"(254.5, 352.5)",254.5,352.5,My silence smile is just another word for my p...,-1,-1,v,87,t-0-1,11,1
30,30,Text,127,239,411,427,16,112,1792,"(183.0, 419.0)",183.0,419.0,Saarah Laten,-1,-1,v,86,t-0,13,1
31,31,Text,127,301,447,461,14,174,2436,"(214.0, 454.0)",214.0,454.0,Sometimes It's better to be alone,-1,-1,v,87,t-0-1,13,1
32,32,Text,126,255,513,529,16,129,2064,"(190.5, 521.0)",190.5,521.0,Alan Leonardo,-1,-1,v,83,t-0,16,1
33,33,Text,128,364,548,563,15,236,3540,"(246.0, 555.5)",246.0,555.5,"I'm not failed ... my success is just postponed ,",-1,-1,v,86,t-0-1,16,1
34,34,Text,127,291,612,629,17,164,2788,"(209.0, 620.5)",209.0,620.5,Alexandra Stevanii,-1,-1,v,86,t-0,18,1
35,35,Text,127,400,649,665,16,273,4368,"(263.5, 657.0)",263.5,657.0,The only way to do great work is to love what ...,-1,-1,v,87,t-0-1,18,1
36,36,Text,127,273,715,730,15,146,2190,"(200.0, 722.5)",200.0,722.5,Soraiea Mertalez,-1,-1,v,81,t-0,20,1
37,37,Text,126,413,752,767,15,287,4305,"(269.5, 759.5)",269.5,759.5,A journey of a thousand miles begins with a si...,-1,-1,v,83,t-0-1,20,1
38,38,Text,127,241,811,833,22,114,2508,"(184.0, 822.0)",184.0,822.0,Lelya Mareen,-1,-1,v,-1,t-0,23,1
39,39,Text,127,385,850,865,15,258,3870,"(256.0, 857.5)",256.0,857.5,"Do not give up , the beginning is always the h...",-1,-1,v,-1,t-0-1,23,1

In [11]:
gui.compos_df.check_group_validity_by_compos_gap(show=True)

In [25]:
compos = gui.compos_df.compos_dataframe

In [26]:
groups = compos.groupby('group').groups  # {group name: list of compo ids}

In [27]:
groups

{-1: Int64Index([3, 10, 14, 22, 24, 25], dtype='int64'),
 'nt-0': Int64Index([8, 11, 13, 16, 18, 20, 23], dtype='int64'),
 'nt-1': Int64Index([2, 4], dtype='int64'),
 'nt-2': Int64Index([9, 12, 15, 17, 19, 21], dtype='int64'),
 'nt-4': Int64Index([5, 6, 7], dtype='int64'),
 'nt-5': Int64Index([0, 1], dtype='int64'),
 't-0': Int64Index([26, 28, 30, 32, 34, 36, 38], dtype='int64'),
 't-0-1': Int64Index([27, 29, 31, 33, 35, 37, 39], dtype='int64')}

In [32]:
group

Int64Index([5, 6, 7], dtype='int64')

In [34]:
group = groups['nt-4']  # list of component ids in the group
gaps = list(compos.loc[group]['gap'])

# cluster compos gaps
eps = 20 if compos.loc[group[0], 'class'] == 'Text' else 10
clustering = DBSCAN(eps=eps, min_samples=1).fit(np.reshape(gaps[:-1], (-1, 1)))
gap_labels = list(clustering.labels_)
gap_label_count = dict((i, gap_labels.count(i)) for i in gap_labels)  # {label: frequency of label}

In [38]:
gaps

[172, 167]

In [ ]:
for i in groups:
    if i == -1: continue
    if len(groups[i]) == 1:
        compos.loc[groups[i][0], 'group'] = -1
    elif len(groups[i]) > 2:
        group = groups[i]  # list of component ids in the group
        gaps = list(compos.loc[group]['gap'])

        # cluster compos gaps
        eps = 20 if compos.loc[group[0], 'class'] == 'Text' else 10
        clustering = DBSCAN(eps=eps, min_samples=1).fit(np.reshape(gaps[:-1], (-1, 1)))
        gap_labels = list(clustering.labels_)
        gap_label_count = dict((i, gap_labels.count(i)) for i in gap_labels)  # {label: frequency of label}

        for label in gap_label_count:
            # invalid compo if the compo's gap with others is different from others
            if gap_label_count[label] < 2:
                for j, lab in enumerate(gap_labels):
                    if lab == label:
                        compos.loc[group[j], 'group'] = -1
                        changed = True

In [63]:
gui.compos_df.compos_dataframe = df

In [6]:
df = gui.compos_df.compos_dataframe

In [8]:
pair = df.groupby('group_pair').groups[1]
pair_all_compos = df.loc[pair]

In [9]:
paired_groups = pair_all_compos.groupby('group').groups

In [10]:
paired_groups

{'nt-0': Int64Index([3, 5, 7], dtype='int64'),
 'nt-1': Int64Index([4, 6, 8], dtype='int64'),
 't-0': Int64Index([12, 14, 16], dtype='int64'),
 't-1': Int64Index([13, 17], dtype='int64')}

In [8]:
gui.cvt_compos_json_to_dataframe()
gui.compos_df.repetitive_group_recognition(show=True)

In [7]:
gui.compos_df.calc_gap_in_group()

In [9]:
df = gui.compos_df.compos_dataframe
g_nt1 = df[df['group'] == 'nt-1']
g_t3 = df[df['group'] == 't-3']

In [10]:
pairing.match_two_groups_by_angles_and_y_distance(g_nt1, g_t3)

[-1, -1] Corner Angles: [1, -2] Center Angles: [10, 3]

D:\Anaconda\lib\site-packages\pandas\core\indexing.py:362: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
D:\Anaconda\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

True